config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cocktails, only: [ :index, :new, :create, :show, :destroy, :edit, :update ] do
    resources :ingredients
    resources :doses, except: [:destroy]
  end

  resources :doses, only: [:destroy]
  root to: 'cocktails#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses , dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, uniqueness: true, presence: true
  validates :photo, presence: true
  mount_uploader :photo, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail

  validates :description, presence: true
  validates :cocktail_id, uniqueness: { scope: :ingredient_id }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses

  validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @doses = @cocktail.doses
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_permits)
    if @cocktail.save
      @dose = Dose.new(dose_permits)
      @dose.cocktail_id = @cocktail.id
      if @dose.save
        redirect_to cocktails_path
      else
        render :new
      end
    else
      render :new
    end
  end

  def edit
    @cocktail = Cocktail.find(params[:id])
  end

  def update
    @cocktail = Cocktail.find(params[:id])
    @cocktail.update(permits)
    redirect_to cocktail_path(@cocktail)
  end

  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy
    redirect_to cocktails_path
  end

  private

  def permits
    params.require(:cocktail).permit(:name, :description, :doses, :photo, :photo_cache)
  end

  def cocktail_permits
    params.require(:cocktail).permit(:name, :doses, :description, :photo, :photo_cache)
  end

  def dose_permits
    params.require(:cocktail).require(:doses).permit(:description, :ingredient_id)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_dose, only: [:show]
  before_action :set_cocktail, only: [:new, :show]

  def new
    @dose = Dose.new
  end

  def show
  end

  def create
    @dose = Dose.new(permits)
    @dose.cocktail_id = params[:cocktail_id]
    if @dose.save
      redirect_to cocktail_path(params[:cocktail_id])
    else
      render :new
    end
  end

  def destroy
    dose = Dose.find(params[:id])
    dose.destroy
    redirect_to cocktail_path(dose.cocktail_id)
  end


  private

  def set_dose
    @dose = Dose.find(params[:id])
  end

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def permits
    params.require(:dose).permit(:description, :ingredient_id)
  end

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doeses_helper.rb
module DoesesHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col col-xs-12 col-md-6 col-md-offset-3">
      <h2> Edit this Cocktail </h2>
      <%= simple_form_for(@cocktail) do |f| %>
        <%= f.input :name %>
        <%= f.input :description %>
        <%= f.input :photo %>
        <%= f.input :photo_cache, as: :hidden %>
        <%= f.submit "Update your Cocktail", class: "btn btn-danger" %>
      <% end %>
    </div>
  </div>
</div>

app/views/cocktails/index.html.erb
<div class="banner" style="background-image: url('https://images.unsplash.com/photo-1504670482337-6863551c6f55?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=60383aeb54a3cbd56dcf5fe1753a01d8&auto=format&fit=crop&w=1950&q=80');">
  <div class = "banner-ds">
    <h1>  </h1>
    <h1>  </h1>
    <h1> Mister Cocktail </h1>
    <%= link_to "Go on add a cocktail", new_cocktail_path, class: "btn btn-danger" %>
  </div>
</div>
<h1 id = "header"> All Cocktails </h1>
<div class = "container">
  <div class = "row">
    <% @cocktails.each do |cocktail| %>
      <div class = "col-xs-4">
        <div class="flat-card">
          <div class='flat-img' style="background-image: url('<%= cl_image_path cocktail.photo %>');"></div>
          <div class = 'flat-text'>
            <h3 class = 'flat-name'> <%= cocktail.name %> </h3>
            <p class = 'flat-description'> Description: <%= cocktail.description %> </p>
          </div>
          <div class = 'flat-text-symbols'>
          </div>
          <div class = 'flat-footer'>
            <p class = 'flat-info'> <%= link_to 'More info', cocktail_path(cocktail)%> </p>
            <p class = 'flat-edit'> <%= link_to 'Edit', edit_cocktail_path(cocktail)%> </p>
            <p class = 'flat-remove'> <%= link_to 'Remove', cocktail_path(cocktail), method: :delete %> </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="container">
  <div class="row">
    <div class="col col-xs-12 col-md-6 col-md-offset-3">
      <h2> Add a New Cocktail</h2>
      <%= simple_form_for(@cocktail) do |f| %>
        <%= f.input :name %>
        <%= f.input :description %>
        <h3> Add a Dose for Your Cocktail </h3>
        <%= f.simple_fields_for :doses do |form| %>
          <%= form.input :description %>
          <%= form.input :ingredient_id, as: :select, collection: Ingredient.all %>
        <% end %>
        <%= f.input :photo %>
        <%= f.input :photo_cache, as: :hidden %>
        <%= f.submit "add a cocktail!", class: "btn btn-danger" %>
      <% end %>
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<div class="photo">
  <%= cl_image_tag @cocktail.photo, class: "image"  %>
</div>
<body id = 'show-body'>
  <div class = 'container'>
    <div class = 'row'>
      <div class = 'col-xs-8'>
        <div class = 'flat-show' >
          <div class = 'flat-show-text'>
            <h3> <%= @cocktail.name %> </h3>
            <h5> <%= @cocktail.description %> </h5>
          </div>
        </div>
      </div>
      <div class = 'col-xs-4'>
        <div class = 'flat-show'>
          <div class = 'flat-show-title'>
            <h3> Ingredients </h3>
            <p id = 'dose-padding'><%= link_to "Add a new dose", new_cocktail_dose_path(@cocktail)  %> </p>
          </div>
          <div class = 'flat-show-text' id = 'doses-alignment'>
            <% @doses.each do |dose| %>
              <p> <%= dose.description %> <%= Ingredient.find(dose.ingredient_id).name %> <%= link_to "delete", dose_path(dose), method: :delete %></p>
            <% end %>
          </div>
        </div>
      </div>
      <div class = 'col-xs-4'>
        <div class = 'flat-show' id = 'show-links'>
          <p> <%= link_to "Back", cocktails_path %> </p>
          <p> <%= link_to "Edit", edit_cocktail_path(@cocktail) %> </p>
          <p> <%= link_to "Delete", cocktail_path(@cocktail), method: :delete %> </p>
        </div>
      </div>
    </div>
  </div>
</div>
</body>

app/views/doses/new.html.erb
<div class = "container">
  <div class = "row">
    <div class = "col-xs-6 col-xs-offset-3">
      <h2> New Dose</h2>
      <%= simple_form_for([@cocktail, @dose]) do |f| %>
        <%= f.input :description %>
        <%= f.association :ingredient %>
        <%= f.submit "add a dose!", class: "btn btn-danger" %>
      <% end %>
    </div>
  </div>
</div>

app/views/doses/show.html.erb
<h1> SHOW </h1>
<h2> @dose.description </h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>